version: "3"
services:
  serviceconnect:
    build: .
    env_file:
    - ./env/.appenv
    ports:
      - "5000:5000"
    depends_on:
      -postgres
  postgres:
    image: postgres:9
    container_name: scpsql
    env_file:
    - ./env/.dbenv
    volumes:
    - ./scdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
volumes:
  scdata: {}
