FROM tiangolo/uwsgi-nginx-flask:python3.6

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install uwsgi
RUN pip install -r requirements.txt

COPY ./app /app

ENV TWILIO_SID $TWILIO_SID
ENV TWILIO_AUTH $TWILIO_AUTH
ENV TWILIO_NUM $TWILIO_NUM
ENV TWILIO_SID_TEST $TWILIO_SID_TEST
ENV TWILIO_AUTH_TEST $TWILIO_AUTH_TEST
ENV TWILIO_NUM_TEST $TWILIO_NUM_TEST
ENV POSTGRES_HOST $POSTGRES_HOST
ENV POSTGRES_DB $POSTGRES_DB
ENV POSTGRES_USER $POSTGRES_USER
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD
ENV ENV $ENV

EXPOSE 80
